### ISSUE TITLE
Negative coordinates are off by 1 (and there are 2 0s)

### ISSUE THREAD

**Issue by Jamcdonald120** [miraisoft-de/mc-fabric-ash#7]
when standing on block -1 as reported by the f3 hud, ASH reports that the block is 0.  It also reports block 0 as block 0, so all negative coordinates are off by 1.  ex standing on block -24 is reported as -23
![image](https://github.com/miraisoft-de/mc-fabric-ash/assets/22623066/ef63829b-e6d6-4df6-8f17-2ebabd3be583)
![image](https://github.com/miraisoft-de/mc-fabric-ash/assets/22623066/7c32c09b-be5a-419d-a5ff-7e78092cbc36)

this can likely be fixed by replacing InGameHeadMixin.java Line 30 with `BlockPos blockPos = cameraEntity().getBlockPos();` but I have not tested this fix.

**Comment by Jamcdonald120** [comment]
I didnt realize master isnt the up to date branch, that fix suggestion was for master

**Comment by miraisoft-de** [comment]
Fixed for main branch "ash2". Will be included in future releases. I'm thinking about fixing older versions too.

**Comment by miraisoft-de** [comment]
Old versions will not be fixed.
